# Generated by Django 6.0.6 on 2026-08-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableimage',
            name='image',
            field=models.FileField(upload_to='timetables/'),
        ),
    ]
