# Generated by Django 6.0.6 on 2026-07-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('08:00-09:00', '08:00 – 09:00'), ('09:00-10:00', '09:00 – 10:00'), ('10:00-11:00', '10:00 – 11:00'), ('11:00-12:00', '11:00 – 12:00'), ('12:00-13:00', '12:00 – 13:00'), ('13:00-14:00', '13:00 – 14:00'), ('14:00-15:00', '14:00 – 15:00'), ('15:00-16:00', '15:00 – 16:00'), ('16:00-17:00', '16:00 – 17:00')], max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='faculty.faculty')),
            ],
            options={
                'ordering': ['day', 'time_slot'],
                'constraints': [models.UniqueConstraint(fields=('department', 'semester', 'day', 'time_slot'), name='unique_timetable_slot')],
            },
        ),
    ]
