# Generated by Django 6.0.6 on 2026-07-06 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('internal', 'Internal'), ('midterm', 'Mid-Term'), ('final', 'Final'), ('practical', 'Practical'), ('assignment', 'Assignment')], default='internal', max_length=20)),
                ('marks_obtained', models.FloatField()),
                ('max_marks', models.FloatField(default=100)),
                ('grade', models.CharField(blank=True, choices=[('O', 'Outstanding (O)'), ('A+', 'Excellent (A+)'), ('A', 'Very Good (A)'), ('B+', 'Good (B+)'), ('B', 'Above Average (B)'), ('C', 'Average (C)'), ('D', 'Pass (D)'), ('F', 'Fail (F)')], max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to='faculty.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'exam_type'), name='unique_marks_per_student_subject_exam')],
            },
        ),
    ]
